source "http://rubygems.org"
source "http://gems.github.com"

gem 'bigdecimal',       ">= 1.1.0"
gem 'bundler',          ">=1.6.3"
gem 'bundler-unload',   ">=1.0.2"
gem 'coderay',          ">=1.1.0"
gem 'executable-hooks', ">=1.3.2"
gem 'gem-wrappers',     ">=1.2.5"
gem 'io-console',       ">=0.3"
gem 'json',             ">=1.5.5"
gem 'method_source',    ">=0.8.2"
gem 'minitest',         ">=2.5.1"
gem 'pry',              ">=0.10.0"
gem 'pry-doc',          ">=0.6.0"
gem 'pry-remote',       ">=0.1.8"
gem 'rake',             ">=0.9.2.2"
gem 'rb-appscript',     ">=0.6.1"
gem 'rdoc',             ">=3.9.5"
gem 'rubygems-bundler', ">=1.4.4"
gem 'rvm',              ">=1.11.3.9"
gem 'slop',             ">=3.5.0"
gem 'yard',             ">=0.8.7.4"
